localStorage.setItem('깔끔왕', 0); 
localStorage.setItem('조용왕', 0); 
localStorage.setItem('열광왕', 0);  
localStorage.setItem('정보왕', 0);  
localStorage.setItem('모범왕', 0);  
localStorage.setItem('돌아이', 0);  
localStorage.setItem('공감왕', 0);  
localStorage.setItem('허당왕', 0);  
localStorage.setItem('보부상', 0);  